# Generated by Django 5.2.17 on 2026-09-28 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_attachment_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_archived', '-created_at', '-id'], name='crm_lead_pager_idx'),
        ),
    ]
